from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime

from signals.base import TradeSignal


@dataclass
class TradePlan:
    """A structured trade plan generated by the AI trade planner."""

    signal: TradeSignal
    entry_price: float
    stop_loss: float
    targets: list[float]
    position_size: float
    risk_amount: float
    rationale: str
    market_context: str
    pattern_quality: str
    risk_reward_analysis: str
    created_at: datetime = field(default_factory=datetime.now)

    def summary(self) -> str:
        direction = self.signal.direction.value.upper()
        rr = self.signal.reward_risk_ratio
        rr_str = f"{rr:.2f}" if rr else "N/A"
        targets_str = ", ".join(f"${t:,.2f}" for t in self.targets)

        return (
            f"TRADE PLAN: {direction} {self.signal.symbol}\n"
            f"{'=' * 50}\n"
            f"Entry: ${self.entry_price:,.2f}\n"
            f"Stop Loss: ${self.stop_loss:,.2f}\n"
            f"Targets: {targets_str}\n"
            f"Risk/Reward: {rr_str}\n"
            f"Position Size: {self.position_size:,.4f} units\n"
            f"Risk Amount: ${self.risk_amount:,.2f}\n"
            f"\nRationale: {self.rationale}\n"
            f"\nMarket Context: {self.market_context}\n"
            f"\nPattern Quality: {self.pattern_quality}\n"
            f"\nRisk/Reward Analysis: {self.risk_reward_analysis}\n"
        )


class TradePlanner:
    """AI-powered trade plan generator.

    When a signal fires, the trade planner creates a structured trade plan
    document that includes market context, pattern quality assessment,
    and risk/reward analysis.
    """

    def __init__(self, llm_client=None, model: str = "claude-sonnet-4-20250514"):
        self._client = llm_client
        self._model = model

    def _get_client(self):
        if self._client is not None:
            return self._client

        try:
            import anthropic
            self._client = anthropic.Anthropic()
            return self._client
        except Exception:
            pass

        try:
            import openai
            self._client = openai.OpenAI()
            self._model = "gpt-4o"
            return self._client
        except Exception:
            return None

    def create_plan(
        self,
        signal: TradeSignal,
        account_equity: float,
        risk_per_trade: float = 0.02,
        position_size: float | None = None,
    ) -> TradePlan:
        """Create a trade plan from a signal.

        Uses AI for rationale and context if available, falls back to
        deterministic analysis if no LLM is configured.
        """
        # Calculate position sizing
        risk_amount = account_equity * risk_per_trade
        if position_size is None:
            risk_per_unit = signal.risk_per_unit
            if risk_per_unit > 0:
                position_size = risk_amount / risk_per_unit
            else:
                position_size = 0.0

        # Get AI analysis if available
        ai_analysis = self._get_ai_analysis(signal)

        return TradePlan(
            signal=signal,
            entry_price=signal.entry_price,
            stop_loss=signal.stop_loss,
            targets=list(signal.targets),
            position_size=position_size,
            risk_amount=risk_amount,
            rationale=ai_analysis.get("rationale", self._default_rationale(signal)),
            market_context=ai_analysis.get("market_context", "No LLM available for context analysis."),
            pattern_quality=ai_analysis.get(
                "pattern_quality",
                f"Confidence: {signal.confidence:.0%}"
            ),
            risk_reward_analysis=ai_analysis.get(
                "risk_reward",
                self._default_risk_analysis(signal, risk_amount),
            ),
        )

    def _get_ai_analysis(self, signal: TradeSignal) -> dict[str, str]:
        """Get AI-generated analysis for the trade plan."""
        client = self._get_client()
        if client is None:
            return {}

        prompt = f"""You are a trading analyst. Provide a brief analysis for this trade setup.

Signal Details:
- Symbol: {signal.symbol}
- Direction: {signal.direction.value}
- Pattern: {signal.pattern_name}
- Entry: ${signal.entry_price:,.4f}
- Stop Loss: ${signal.stop_loss:,.4f}
- Targets: {[f"${t:,.4f}" for t in signal.targets]}
- Risk/Reward: {signal.reward_risk_ratio or "N/A"}
- Confidence: {signal.confidence:.0%}
- Pattern Details: {json.dumps(signal.metadata, default=str)}

Respond in JSON format with these keys:
- "rationale": 1-2 sentence trade rationale
- "market_context": Brief market context note
- "pattern_quality": Assessment of pattern quality
- "risk_reward": Risk/reward analysis

Keep each field to 1-3 sentences. Be specific and actionable."""

        try:
            response = self._call_llm(prompt)
            # Try to parse JSON from response
            # Handle case where response has markdown code blocks
            text = response.strip()
            if text.startswith("```"):
                text = text.split("\n", 1)[1].rsplit("```", 1)[0]
            return json.loads(text)
        except (json.JSONDecodeError, Exception):
            return {}

    def _call_llm(self, prompt: str) -> str:
        client = self._get_client()
        if client is None:
            return ""

        if hasattr(client, "messages"):
            response = client.messages.create(
                model=self._model,
                max_tokens=500,
                messages=[{"role": "user", "content": prompt}],
            )
            return response.content[0].text
        else:
            response = client.chat.completions.create(
                model=self._model,
                messages=[{"role": "user", "content": prompt}],
                max_tokens=500,
            )
            return response.choices[0].message.content

    @staticmethod
    def _default_rationale(signal: TradeSignal) -> str:
        direction = signal.direction.value
        rr = signal.reward_risk_ratio
        rr_str = f"{rr:.1f}:1 R:R" if rr else ""
        return (
            f"{signal.pattern_name} {direction} setup on {signal.symbol}. "
            f"Confidence {signal.confidence:.0%}. {rr_str}"
        )

    @staticmethod
    def _default_risk_analysis(signal: TradeSignal, risk_amount: float) -> str:
        rr = signal.reward_risk_ratio
        if rr and rr >= 2.0:
            quality = "Favorable"
        elif rr and rr >= 1.0:
            quality = "Acceptable"
        else:
            quality = "Below ideal threshold"

        return (
            f"{quality} risk/reward of {rr:.1f}:1. "
            f"Risking ${risk_amount:,.2f} per trade."
            if rr
            else f"Risking ${risk_amount:,.2f} per trade."
        )
